FROM alpine:3

LABEL author="Mikail Yuma Anri Malino"
LABEL company="Institut Teknologi Kalimantan" website="https://itk.ac.id/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"